import { $, circled, fmt, parseNumber } from './utils.js';
export class CalibrationController {
  constructor(ui, transform) { this.ui = ui; this.transform = transform; this.viewer = null; this.points = []; this.lastReport = null; this.pending = null; this.editIndex = null; }
  attachViewer(viewer) { this.viewer = viewer; }
  open() { this.renderList(); this.ui.openDialog('dlgCalib'); }
  startAdd() { if (!this.viewer.bitmap) { this.ui.toast('先に図面を読み込んでください'); return; } if (this.points.length >= 4) { this.ui.toast('標定点は最大4点です'); return; } this.ui.closeDialog('dlgCalib'); this.ui.showTapBanner('標定点の位置をタップしてください'); this.viewer.tapHandler = (u, v) => { this.pending = { u, v }; this.editIndex = null; $('calibX').value = ''; $('calibY').value = ''; this.ui.openDialog('dlgCoordInput'); }; }
  edit(index) { const point = this.points[index]; this.pending = { u: point.u, v: point.v }; this.editIndex = index; $('calibX').value = point.X; $('calibY').value = point.Y; this.ui.openDialog('dlgCoordInput'); }
  confirmCoord() { try { if (!this.pending) return; const point = { ...this.pending, X: parseNumber($('calibX').value, 'X'), Y: parseNumber($('calibY').value, 'Y') }; if (this.editIndex === null) this.points.push(point); else this.points[this.editIndex] = point; this.pending = null; this.editIndex = null; this.ui.closeDialog('dlgCoordInput'); this.compute(true); this.open(); this.viewer.requestRender(); } catch (error) { this.ui.toast(error.message); } }
  remove(index) { this.points.splice(index, 1); this.compute(true); this.renderList(); this.viewer.requestRender(); }
  clearAll() { this.points = []; this.lastReport = null; this.transform.restore(null); this.ui.setRmse(null); this.renderList(); this.viewer.requestRender(); }
  compute(silent = false) { if (this.points.length < 2) { this.lastReport = null; this.transform.restore(null); this.ui.setRmse(null); if (!silent) this.ui.toast('標定点が不足しています'); return false; } try { this.lastReport = this.transform.compute(this.points); this.ui.setRmse(this.lastReport.rmse); this.viewer.requestRender(); return true; } catch (error) { this.lastReport = null; this.ui.toast(error.message || '標定計算に失敗しました'); return false; } }
  renderList() { const list = $('calibList'); list.innerHTML = ''; if (this.points.length === 0) list.innerHTML = '<li class="empty">標定点はありません</li>'; this.points.forEach((p, i) => { const li = document.createElement('li'); const residual = this.lastReport ? this.lastReport.residuals[i] : null; li.innerHTML = `<span class="grow">${circled(i + 1)} X=${fmt(p.X)} Y=${fmt(p.Y)}<span class="sub">画像(${fmt(p.u,1)}, ${fmt(p.v,1)})px${residual ? ` / 残差 ${fmt(residual.distance, 3)}m` : ''}</span></span>`; const edit = document.createElement('button'); edit.textContent = '編集'; edit.addEventListener('click', () => this.edit(i)); const del = document.createElement('button'); del.className = 'danger'; del.textContent = '削除'; del.addEventListener('click', () => this.remove(i)); li.append(edit, del); list.appendChild(li); }); $('calibRmse').textContent = this.lastReport ? `${this.lastReport.type}変換 / RMSE ${fmt(this.lastReport.rmse, 3)}m / ${this.points.length}点` : ''; }
  serialize() { return this.points.slice(); }
  restore(points) { this.points = Array.isArray(points) ? points : []; this.compute(true); }
}
