import { $, APP, downloadJson, nowIso, readFileAsArrayBuffer, uuid } from './utils.js';
export class ProjectController {
  constructor(ui, storage, viewer, calibration, candidates, transform, gps) { this.ui = ui; this.storage = storage; this.viewer = viewer; this.calibration = calibration; this.candidates = candidates; this.transform = transform; this.gps = gps; this.current = { id: uuid(), name: '', area: '', zone: 1, createdAt: nowIso(), updatedAt: nowIso(), drawing: null, view: null }; }
  async setDrawing(file) { const bytes = await readFileAsArrayBuffer(file); const type = file.type || this.detectType(file.name); switch (true) { case type === 'application/pdf': await this.viewer.loadPDF(bytes); break; case type === 'image/png' || type === 'image/jpeg': await this.viewer.loadImage(bytes, type); break; default: throw new Error('対応していないファイル形式です'); } this.current.drawing = { name: file.name, type, data: Array.from(new Uint8Array(bytes)) }; }
  detectType(name) { const lower = name.toLowerCase(); if (lower.endsWith('.pdf')) return 'application/pdf'; if (lower.endsWith('.png')) return 'image/png'; if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'image/jpeg'; return ''; }
  capture() { this.current.name = $('prjName').value.trim(); this.current.area = $('prjArea').value.trim(); this.current.zone = Number($('prjZone').value) || 1; this.current.updatedAt = nowIso(); this.current.view = { ...this.viewer.view }; this.current.calibration = this.calibration.serialize(); this.current.transform = this.transform.serialize(); this.current.candidates = this.candidates.serialize(); return this.current; }
  async save() { try { const project = this.capture(); await this.storage.putProject(project); await this.storage.putMeta(APP.autosaveKey, project.id); this.ui.toast('保存しました'); await this.renderList(); } catch (error) { this.ui.toast(error.message || '保存に失敗しました'); } }
  async loadLast() { const id = await this.storage.getMeta(APP.autosaveKey); if (id) { const project = await this.storage.getProject(id); if (project) await this.restore(project); } }
  async restore(project) { this.current = project; $('prjName').value = project.name || ''; $('prjArea').value = project.area || ''; $('prjZone').value = String(project.zone || 1); this.gps.setZone(project.zone || 1); this.calibration.restore(project.calibration); this.transform.restore(project.transform); this.candidates.restore(project.candidates); if (project.drawing && project.drawing.data) { const bytes = new Uint8Array(project.drawing.data).buffer; if (project.drawing.type === 'application/pdf') await this.viewer.loadPDF(bytes); else await this.viewer.loadImage(bytes, project.drawing.type); } if (project.view) { this.viewer.view = project.view; this.viewer.requestRender(); } this.ui.toast('プロジェクトを読み込みました'); }
  newProject() { this.current = { id: uuid(), name: '', area: '', zone: Number($('prjZone').value) || 1, createdAt: nowIso(), updatedAt: nowIso(), drawing: null, view: null }; $('prjName').value = ''; $('prjArea').value = ''; this.viewer.clear(); this.calibration.restore([]); this.transform.restore(null); this.candidates.restore([]); this.ui.setRmse(null); this.ui.toast('新規プロジェクトを作成しました'); }
  async renderList() { const list = $('prjList'); const projects = await this.storage.listProjects(); list.innerHTML = ''; if (!projects.length) { list.innerHTML = '<li class="empty">保存済みプロジェクトはありません</li>'; return; } projects.sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt))).forEach((project) => { const li = document.createElement('li'); li.innerHTML = `<span class="grow">${project.name || '名称未設定'}<span class="sub">${project.area || ''} ${new Date(project.updatedAt).toLocaleString('ja-JP')}</span></span>`; const load = document.createElement('button'); load.textContent = '読込'; load.addEventListener('click', () => this.restore(project)); li.appendChild(load); list.appendChild(li); }); }
  exportJSON() { const name = (this.current.name || 'base-point-project').replace(/[\\/:*?"<>|]/g, '_'); downloadJson(`${name}.json`, this.capture()); }
  async importJSON(file) { try { const text = await file.text(); const project = JSON.parse(text); project.id = project.id || uuid(); await this.restore(project); await this.save(); } catch (error) { this.ui.toast('JSON読込に失敗しました'); } }
}
