export class TransformService {
  constructor() { this.params = null; this.type = null; }
  compute(points) { if (!Array.isArray(points) || points.length < 2) throw new Error('標定点が不足しています'); if (points.length > 4) throw new Error('標定点は最大4点です'); const params = points.length === 2 ? this.computeHelmert(points) : this.computeAffine(points); const det = params.a * params.e - params.b * params.d; if (!Number.isFinite(det) || Math.abs(det) < 1e-12) throw new Error('標定計算に失敗しました。点の配置を確認してください'); this.params = params; this.type = points.length === 2 ? '相似' : 'アフィン'; return this.report(points); }
  computeHelmert(points) { const n = Array.from({ length: 4 }, () => [0,0,0,0]); const b = [0,0,0,0]; const add = (row, value) => row.forEach((ri, i) => { b[i] += ri * value; row.forEach((rj, j) => { n[i][j] += ri * rj; }); }); points.forEach((p) => { add([p.u, p.v, 1, 0], p.Y); add([-p.v, p.u, 0, 1], p.X); }); const s = this.solve(n, b); if (!s) throw new Error('相似変換を解けませんでした'); const [ar, br, y0, x0] = s; return { a: br, b: -ar, c: x0, d: ar, e: br, f: y0 }; }
  computeAffine(points) { const n = [[0,0,0],[0,0,0],[0,0,0]]; const bx = [0,0,0]; const by = [0,0,0]; points.forEach((p) => { const row = [p.u, p.v, 1]; row.forEach((ri, i) => { bx[i] += ri * p.X; by[i] += ri * p.Y; row.forEach((rj, j) => { n[i][j] += ri * rj; }); }); }); const sx = this.solve(n.map((r) => r.slice()), bx.slice()); const sy = this.solve(n.map((r) => r.slice()), by.slice()); if (!sx || !sy) throw new Error('アフィン変換を解けませんでした'); return { a: sx[0], b: sx[1], c: sx[2], d: sy[0], e: sy[1], f: sy[2] }; }
  solve(matrix, rhs) { const size = rhs.length; for (let col = 0; col < size; col += 1) { let pivot = col; for (let row = col + 1; row < size; row += 1) if (Math.abs(matrix[row][col]) > Math.abs(matrix[pivot][col])) pivot = row; if (Math.abs(matrix[pivot][col]) < 1e-12) return null; [matrix[col], matrix[pivot]] = [matrix[pivot], matrix[col]]; [rhs[col], rhs[pivot]] = [rhs[pivot], rhs[col]]; const div = matrix[col][col]; for (let c = col; c < size; c += 1) matrix[col][c] /= div; rhs[col] /= div; for (let row = 0; row < size; row += 1) { if (row === col) continue; const factor = matrix[row][col]; for (let c = col; c < size; c += 1) matrix[row][c] -= factor * matrix[col][c]; rhs[row] -= factor * rhs[col]; } } return rhs; }
  imageToGround(u, v) { const p = this.params; return p ? { X: p.a * u + p.b * v + p.c, Y: p.d * u + p.e * v + p.f } : null; }
  groundToImage(X, Y) { const p = this.params; if (!p) return null; const det = p.a * p.e - p.b * p.d; return { u: (p.e * (X - p.c) - p.b * (Y - p.f)) / det, v: (-p.d * (X - p.c) + p.a * (Y - p.f)) / det }; }
  metersPerPixel() { if (!this.params) return null; const p = this.params; return Math.sqrt(Math.abs(p.a * p.e - p.b * p.d)); }
  report(points) { const residuals = points.map((point) => { const actual = this.imageToGround(point.u, point.v); const dX = actual.X - point.X; const dY = actual.Y - point.Y; return { dX, dY, distance: Math.hypot(dX, dY) }; }); const sum = residuals.reduce((acc, r) => acc + r.dX * r.dX + r.dY * r.dY, 0); return { type: this.type, residuals, rmse: Math.sqrt(sum / points.length) }; }
  serialize() { return this.params ? { params: this.params, type: this.type } : null; }
  restore(data) { this.params = data && data.params ? data.params : null; this.type = data && data.type ? data.type : null; }
}
