import { APP, $, clamp, debugError, debugLog, isVisible } from './utils.js';
export class Viewer {
  constructor(ui, transform, gps, calibration, candidates) { this.ui = ui; this.transform = transform; this.gps = gps; this.calibration = calibration; this.candidates = candidates; this.canvas = null; this.ctx = null; this.container = null; this.bitmap = null; this.imageWidth = 0; this.imageHeight = 0; this.view = { scale: 1, tx: 0, ty: 0 }; this.tapHandler = null; this.raf = 0; this.touch = null; this.lastTap = { time: 0, x: 0, y: 0 }; }
  init() { this.canvas = $('viewerCanvas'); this.ctx = this.canvas.getContext('2d'); this.container = $('viewerContainer'); this.resize(); window.addEventListener('resize', () => { this.resize(); this.requestRender(); }); this.bindTouch(); this.bindMouse(); }
  async loadPDF(arrayBuffer) { if (!globalThis.pdfjsLib) throw new Error('PDF.jsが読み込まれていません'); debugLog('PDF読込開始'); const bytes = arrayBuffer instanceof Uint8Array ? arrayBuffer : new Uint8Array(arrayBuffer); const pdfData = new Uint8Array(bytes); let doc = null; try { doc = await this.openPdfDocument(pdfData, false); } catch (workerError) { debugError(workerError, 'PDF worker読込失敗。Safari互換フォールバックとしてworker無効で再試行します'); doc = await this.openPdfDocument(new Uint8Array(bytes), true); } try { debugLog('PDF解析成功'); debugLog('ページ数', doc.numPages); const page = await doc.getPage(1); const base = page.getViewport({ scale: 1 }); const scale = Math.min(4, APP.pdfMaxSidePx / Math.max(base.width, base.height)); const viewport = page.getViewport({ scale }); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(viewport.width)); canvas.height = Math.max(1, Math.round(viewport.height)); const context = canvas.getContext('2d', { alpha: false }); if (!context) throw new Error('PDF描画用Canvasを作成できません'); debugLog('Canvas描画開始'); await page.render({ canvasContext: context, viewport }).promise; debugLog('Canvas描画完了'); page.cleanup(); this.setBitmap(canvas); } catch (error) { debugError(error, 'PDF解析またはCanvas描画に失敗しました'); throw new Error(`PDF読込に失敗しました: ${error.message || '不明なエラー'}`); } finally { if (doc && typeof doc.destroy === 'function') doc.destroy(); } }
  async openPdfDocument(data, disableWorker) { const task = globalThis.pdfjsLib.getDocument({ data, disableWorker, useWorkerFetch: false, isEvalSupported: false, useSystemFonts: true }); return task.promise; }
  async loadImage(arrayBuffer, mime) { const blob = new Blob([arrayBuffer], { type: mime }); const url = URL.createObjectURL(blob); try { const image = await new Promise((resolve, reject) => { const img = new Image(); img.onload = () => resolve(img); img.onerror = () => reject(new Error('画像読込に失敗しました')); img.src = url; }); this.setBitmap(image); } finally { setTimeout(() => URL.revokeObjectURL(url), 1000); } }
  setBitmap(bitmap) { this.bitmap = bitmap; this.imageWidth = bitmap.width; this.imageHeight = bitmap.height; $('viewerHint').hidden = true; this.fit(); }
  clear() { this.bitmap = null; this.imageWidth = 0; this.imageHeight = 0; $('viewerHint').hidden = false; this.requestRender(); }
  resize() { const dpr = window.devicePixelRatio || 1; const width = this.container.clientWidth; const height = this.container.clientHeight; this.canvas.width = Math.max(1, Math.round(width * dpr)); this.canvas.height = Math.max(1, Math.round(height * dpr)); this.canvas.style.width = `${width}px`; this.canvas.style.height = `${height}px`; }
  fit() { if (!this.bitmap) return; const width = this.container.clientWidth; const height = this.container.clientHeight; const scale = Math.min(width / this.imageWidth, height / this.imageHeight) * 0.96; this.view = { scale, tx: (width - this.imageWidth * scale) / 2, ty: (height - this.imageHeight * scale) / 2 }; this.requestRender(); }
  screenToImage(x, y) { return { u: (x - this.view.tx) / this.view.scale, v: (y - this.view.ty) / this.view.scale }; }
  imageToScreen(u, v) { return { x: u * this.view.scale + this.view.tx, y: v * this.view.scale + this.view.ty }; }
  zoomAt(x, y, factor) { const next = clamp(this.view.scale * factor, APP.minScale, APP.maxScale); const ratio = next / this.view.scale; this.view.tx = x - (x - this.view.tx) * ratio; this.view.ty = y - (y - this.view.ty) * ratio; this.view.scale = next; this.requestRender(); }
  requestRender() { if (this.raf) return; this.raf = requestAnimationFrame(() => { this.raf = 0; this.render(); }); }
  render() { const dpr = window.devicePixelRatio || 1; this.ctx.setTransform(1,0,0,1,0,0); this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height); this.ctx.setTransform(dpr,0,0,dpr,0,0); if (this.bitmap) { this.ctx.imageSmoothingEnabled = this.view.scale < 3; this.ctx.drawImage(this.bitmap, this.view.tx, this.view.ty, this.imageWidth * this.view.scale, this.imageHeight * this.view.scale); } this.drawCalibration(); this.drawCandidates(); this.drawGps(); this.ui.setZoom(this.view.scale); }
  drawCalibration() { this.calibration.points.forEach((point, index) => { const s = this.imageToScreen(point.u, point.v); this.ctx.strokeStyle = '#1f6fd0'; this.ctx.fillStyle = '#1f6fd0'; this.ctx.lineWidth = 2; this.ctx.beginPath(); this.ctx.moveTo(s.x - 12, s.y); this.ctx.lineTo(s.x + 12, s.y); this.ctx.moveTo(s.x, s.y - 12); this.ctx.lineTo(s.x, s.y + 12); this.ctx.stroke(); this.ctx.beginPath(); this.ctx.arc(s.x, s.y, 8, 0, Math.PI * 2); this.ctx.stroke(); this.label(`P${index + 1}`, s.x + 12, s.y - 12, '#1f6fd0'); }); }
  drawCandidates() { if (!this.transform.params) return; this.candidates.list.forEach((candidate) => { const image = this.transform.groundToImage(candidate.X, candidate.Y); const s = this.imageToScreen(image.u, image.v); this.ctx.strokeStyle = '#d93a35'; this.ctx.fillStyle = '#d93a35'; this.ctx.lineWidth = 2.5; this.ctx.beginPath(); this.ctx.arc(s.x, s.y, 9, 0, Math.PI * 2); this.ctx.stroke(); this.ctx.beginPath(); this.ctx.arc(s.x, s.y, 3, 0, Math.PI * 2); this.ctx.fill(); this.label(candidate.no, s.x + 12, s.y + 4, '#d93a35'); }); }
  drawGps() { if (!this.transform.params || !this.gps.active || !this.gps.last) return; const image = this.transform.groundToImage(this.gps.last.X, this.gps.last.Y); const s = this.imageToScreen(image.u, image.v); const mpp = this.transform.metersPerPixel(); if (mpp && this.gps.last.accuracy) { const radius = (this.gps.last.accuracy / mpp) * this.view.scale; if (radius > 3 && radius < 5000) { this.ctx.fillStyle = 'rgba(0,112,220,0.14)'; this.ctx.strokeStyle = 'rgba(0,112,220,0.55)'; this.ctx.beginPath(); this.ctx.arc(s.x, s.y, radius, 0, Math.PI * 2); this.ctx.fill(); this.ctx.stroke(); } } this.ctx.fillStyle = '#0070dc'; this.ctx.strokeStyle = '#ffffff'; this.ctx.lineWidth = 3; this.ctx.beginPath(); this.ctx.arc(s.x, s.y, 8, 0, Math.PI * 2); this.ctx.fill(); this.ctx.stroke(); if (!isVisible(s, this.container.clientWidth, this.container.clientHeight)) this.ui.toast('現在地が画面外です', 1200); }
  label(text, x, y, color) { this.ctx.font = 'bold 13px -apple-system, BlinkMacSystemFont, sans-serif'; this.ctx.lineWidth = 4; this.ctx.strokeStyle = 'rgba(255,255,255,0.9)'; this.ctx.strokeText(text, x, y); this.ctx.fillStyle = color; this.ctx.fillText(text, x, y); }
  bindTouch() { this.canvas.addEventListener('touchstart', (e) => this.onTouchStart(e), { passive: false }); this.canvas.addEventListener('touchmove', (e) => this.onTouchMove(e), { passive: false }); this.canvas.addEventListener('touchend', (e) => this.onTouchEnd(e), { passive: false }); this.canvas.addEventListener('touchcancel', () => { this.touch = null; }, { passive: false }); }
  touchPos(touch) { const r = this.canvas.getBoundingClientRect(); return { x: touch.clientX - r.left, y: touch.clientY - r.top }; }
  onTouchStart(e) { e.preventDefault(); if (e.touches.length === 1) { const p = this.touchPos(e.touches[0]); this.touch = { mode: 'pan', startX: p.x, startY: p.y, lastX: p.x, lastY: p.y, startTime: Date.now(), moved: false }; } else if (e.touches.length === 2) { const p1 = this.touchPos(e.touches[0]); const p2 = this.touchPos(e.touches[1]); this.touch = { mode: 'pinch', startDistance: Math.hypot(p2.x - p1.x, p2.y - p1.y), startScale: this.view.scale, startTx: this.view.tx, startTy: this.view.ty, midX: (p1.x + p2.x) / 2, midY: (p1.y + p2.y) / 2 }; } }
  onTouchMove(e) { e.preventDefault(); if (!this.touch) return; if (this.touch.mode === 'pan' && e.touches.length === 1) { const p = this.touchPos(e.touches[0]); if (Math.hypot(p.x - this.touch.startX, p.y - this.touch.startY) > APP.tapMovePx) this.touch.moved = true; this.view.tx += p.x - this.touch.lastX; this.view.ty += p.y - this.touch.lastY; this.touch.lastX = p.x; this.touch.lastY = p.y; this.requestRender(); } else if (this.touch.mode === 'pinch' && e.touches.length === 2) { const p1 = this.touchPos(e.touches[0]); const p2 = this.touchPos(e.touches[1]); const distance = Math.hypot(p2.x - p1.x, p2.y - p1.y); const midX = (p1.x + p2.x) / 2; const midY = (p1.y + p2.y) / 2; const scale = clamp(this.touch.startScale * (distance / this.touch.startDistance), APP.minScale, APP.maxScale); const ratio = scale / this.touch.startScale; this.view.scale = scale; this.view.tx = midX - (this.touch.midX - this.touch.startTx) * ratio; this.view.ty = midY - (this.touch.midY - this.touch.startTy) * ratio; this.requestRender(); } }
  onTouchEnd(e) { e.preventDefault(); if (this.touch && this.touch.mode === 'pan' && e.touches.length === 0 && !this.touch.moved && Date.now() - this.touch.startTime < 400) this.onTap(this.touch.startX, this.touch.startY); if (e.touches.length === 0) this.touch = null; }
  onTap(x, y) { const now = Date.now(); if (now - this.lastTap.time < APP.doubleTapMs && Math.hypot(x - this.lastTap.x, y - this.lastTap.y) < 40) { this.lastTap = { time: 0, x: 0, y: 0 }; this.zoomAt(x, y, 2); return; } this.lastTap = { time: now, x, y }; setTimeout(() => { if (this.lastTap.time !== now) return; this.lastTap = { time: 0, x: 0, y: 0 }; this.singleTap(x, y); }, APP.doubleTapMs + 20); }
  singleTap(x, y) { if (!this.bitmap) return; const image = this.screenToImage(x, y); if (this.tapHandler) { const handler = this.tapHandler; this.tapHandler = null; this.ui.hideTapBanner(); handler(image.u, image.v); return; } this.openCandidateAt(x, y); }
  openCandidateAt(x, y) { if (!this.transform.params) return; const hit = this.candidates.list.find((candidate) => { const image = this.transform.groundToImage(candidate.X, candidate.Y); const point = this.imageToScreen(image.u, image.v); return Math.hypot(point.x - x, point.y - y) < APP.hitRadiusPx; }); if (hit) this.candidates.openDetail(hit.id); }
  bindMouse() { let drag = null; this.canvas.addEventListener('mousedown', (event) => { drag = { x: event.clientX, y: event.clientY, moved: false }; }); window.addEventListener('mousemove', (event) => { if (!drag) return; const dx = event.clientX - drag.x; const dy = event.clientY - drag.y; if (Math.hypot(dx, dy) > 4) drag.moved = true; this.view.tx += dx; this.view.ty += dy; drag.x = event.clientX; drag.y = event.clientY; this.requestRender(); }); window.addEventListener('mouseup', (event) => { if (drag && !drag.moved) { const r = this.canvas.getBoundingClientRect(); this.singleTap(event.clientX - r.left, event.clientY - r.top); } drag = null; }); this.canvas.addEventListener('wheel', (event) => { event.preventDefault(); const r = this.canvas.getBoundingClientRect(); this.zoomAt(event.clientX - r.left, event.clientY - r.top, event.deltaY < 0 ? 1.15 : 1 / 1.15); }, { passive: false }); }
}
